param(
  [string]$OutputPath = "docs/CURRENT_STATUS.md"
)

$ErrorActionPreference = "Stop"

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $scriptRoot
$resolvedOutputPath = $OutputPath
if (-not [System.IO.Path]::IsPathRooted($resolvedOutputPath)) {
  $resolvedOutputPath = Join-Path $repoRoot $resolvedOutputPath
}

$branch = ""
try {
  $branch = ((& git branch --show-current 2>$null) | Out-String).Trim()
} catch {
  $branch = ""
}
if ([string]::IsNullOrWhiteSpace($branch)) {
  $branch = "unknown"
}

$hasCommit = $false
try {
  & git rev-parse --verify HEAD *> $null
  if ($LASTEXITCODE -eq 0) {
    $hasCommit = $true
  }
} catch {
  $hasCommit = $false
}

$statusLines = @()
try {
  $statusLines = @(& git status --porcelain=v1 2>$null)
} catch {
  $statusLines = @()
}

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz"

$staged = 0
$unstaged = 0
$untracked = 0

foreach ($line in $statusLines) {
  if ($line.StartsWith("??")) {
    $untracked++
    continue
  }

  if ($line.Length -ge 2) {
    if ($line[0] -ne " ") {
      $staged++
    }
    if ($line[1] -ne " ") {
      $unstaged++
    }
  }
}

$recentSourceFiles = Get-ChildItem -Path $repoRoot -Recurse -File -Force |
  Where-Object {
    $_.FullName -notmatch "\\.git\\" -and
    $_.FullName -notmatch "\\node_modules\\" -and
    $_.FullName -notmatch "\\dist\\" -and
    $_.FullName -notmatch "\\target\\"
  } |
  Sort-Object LastWriteTime -Descending |
  Select-Object -First 10

$recentDocFiles = Get-ChildItem -Path (Join-Path $repoRoot "docs") -File -ErrorAction SilentlyContinue |
  Sort-Object LastWriteTime -Descending |
  Select-Object -First 5

$recentSourceLines = @()
foreach ($file in $recentSourceFiles) {
  $relativePath = $file.FullName.Substring($repoRoot.Length + 1).Replace('\', '/')
  $recentSourceLines += ("- {0} | {1}" -f $relativePath, $file.LastWriteTime.ToString("yyyy-MM-dd HH:mm:ss zzz"))
}
if ($recentSourceLines.Count -eq 0) {
  $recentSourceLines += "- none"
}

$recentDocLines = @()
foreach ($file in $recentDocFiles) {
  $relativePath = $file.FullName.Substring($repoRoot.Length + 1).Replace('\', '/')
  $recentDocLines += ("- {0} | {1}" -f $relativePath, $file.LastWriteTime.ToString("yyyy-MM-dd HH:mm:ss zzz"))
}
if ($recentDocLines.Count -eq 0) {
  $recentDocLines += "- none"
}

$repoSummary = "Repository has commit history."
if (-not $hasCommit) {
  $repoSummary = "Repository has no commits yet."
}

$content = @(
  "# Current Status Snapshot",
  "",
  "> This file is generated by npm run handoff:update.",
  "> Use it as the objective checkpoint for the next session.",
  "",
  "## Updated At",
  "",
  ("- {0}" -f $timestamp),
  "",
  "## Repo Status",
  "",
  ("- {0}" -f $repoSummary),
  ("- Branch: {0}" -f $branch),
  ("- Staged files: {0}" -f $staged),
  ("- Unstaged files: {0}" -f $unstaged),
  ("- Untracked files: {0}" -f $untracked),
  "",
  "## Recent Source Changes",
  ""
)

$content += $recentSourceLines
$content += @(
  "",
  "## Recent Docs",
  ""
)
$content += $recentDocLines
$content += @(
  "",
  "## Next Session Prompt",
  "",
  "- Read docs/NEXT_SESSION_BRIEF.md and docs/CURRENT_STATUS.md first.",
  "- Then summarize current progress, risks, and the best next step before making changes.",
  ""
)

$targetDir = Split-Path -Parent $resolvedOutputPath
if ($targetDir -and -not (Test-Path $targetDir)) {
  New-Item -ItemType Directory -Path $targetDir | Out-Null
}

Set-Content -Path $resolvedOutputPath -Value $content -Encoding UTF8
Write-Output ("Updated {0}" -f $resolvedOutputPath)
